# Makefile generated by makebreed
# http://makebreed.googlecode.com

# Creation Time: 'Wed Apr  3 13:05:03 CEST 2013'

PKGNAME = ffmpegyag
PKGVERSION = 0.6.0
PKGSECTION = video
PKGAUTHOR = Ronny Wegener <wegener.ronny@gmail.com>
PKGHOMEAGE = http://ffmpegyag.googlecode.com
PKGDEPENDS = ffmpeg
PKGDESCRIPTION = A GTK based GUI for ffmpeg\n\
 FFmpegYAG is a GUI for the popular FFmpeg audio/video encoding tool\n\
 .

SRCPATTERN = *.cpp
SRCDIR = src
OBJDIR = obj
DISTROOT = dist/linux
BINFILE = dist/linux/usr/bin/ffmpegyag

CC = g++
CFLAGS = -c -Wall -O2 -I/usr/lib/wx/include/gtk2-unicode-release-static-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread
LD = g++
LDFLAGS = -s
LDLIBS = /usr/lib/libwx_gtk2u_gl-2.8.a -lGL -lGLU -pthread -L/usr/lib/x86_64-linux-gnu /usr/lib/libwx_gtk2u-2.8.a -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgthread-2.0 -lrt -lglib-2.0 -lXinerama -lXxf86vm -lSM -lpng -lz -ljpeg -ltiff -lwxexpat-2.8 -lz -ldl -lm -lavformat -lavcodec -lswscale

SRCFILES := $(shell find $(SRCDIR) -type f -name '' $(addprefix -or -name , $(SRCPATTERN)))

OBJFILES := $(patsubst $(SRCDIR)/%, $(OBJDIR)/%.o, $(SRCFILES))

DISTFILES := $(patsubst $(DISTROOT)%, %, $(shell find $(DISTROOT) -type f))
DISTDIRECTORIES := $(patsubst $(DISTROOT)%, %, $(shell find $(DISTROOT) -type d -empty))

TGZPKG := $(PKGNAME)_$(PKGVERSION).tar.gz
DEBPKG := $(PKGNAME)_$(PKGVERSION)_$(shell dpkg --print-architecture).deb

all: $(BINFILE)
		
$(BINFILE): $(OBJFILES)
		@echo 
		@$(shell mkdir -p $(dir $@))
		$(LD) $(LDFLAGS) -o $@ $^ $(LDLIBS)

$(CURDIR)/$(OBJDIR)/%.o $(CURDIR)/$(SRCDIR)/%.o $(SRCDIR)/%.o: $(OBJDIR)/%.o
		
$(OBJDIR)/%.o: $(SRCDIR)/%
		@echo 
		@$(shell mkdir -p $(dir $@))
		$(CC) $(CFLAGS) -o $@ $<
		@gcc $(CFLAGS) -MM -MT $@ $< >> $(OBJDIR)/$*.depend

-include $(OBJFILES:.o=.depend)

clean:
		@rm -f $(OBJFILES) $(OBJFILES:.o=.depend) $(BINFILE)

install:
		@cp -v -r $(DISTROOT)/* /
		@update-menus

uninstall:
		@rm -v -f $(DISTFILES) 2> /dev/null
		@rmdir -p --ignore-fail-on-non-empty $(DISTDIRECTORIES) 2> /dev/null
		@rmdir -p --ignore-fail-on-non-empty $(dir $(DISTFILES)) 2> /dev/null
		@update-menus

tgz:
		@tar -v -c -z --exclude='$(TGZPKG)' --exclude='make*' --exclude='*.deb' --exclude='$(BINFILE)' --exclude='$(OBJDIR)/*' -f $(TGZPKG) *

deb: all
		@mkdir -p $(DISTROOT)/DEBIAN 2> /dev/null
		@echo 'Package: ffmpegyag' > $(DISTROOT)/DEBIAN/control
		@echo 'Version: 0.6.0' >> $(DISTROOT)/DEBIAN/control
		@echo 'Section: video' >> $(DISTROOT)/DEBIAN/control
		@echo 'Architecture: amd64' >> $(DISTROOT)/DEBIAN/control
		@echo 'Installed-Size: $(shell du -k -c dist/linux | grep 'total' | sed -e 's|\s*total||g')' >> $(DISTROOT)/DEBIAN/control
		@echo 'Depends: $(RESOLVE_PKG_DEPS)' | sed -e 's|,$$||g' >> $(DISTROOT)/DEBIAN/control
		@echo 'Maintainer: Ronny Wegener <wegener.ronny@gmail.com>' >> $(DISTROOT)/DEBIAN/control
		@echo 'Priority: extra' >> $(DISTROOT)/DEBIAN/control
		@echo 'Homepage: http://ffmpegyag.googlecode.com' >> $(DISTROOT)/DEBIAN/control
		@echo 'Description: $(PKGDESCRIPTION)' >> $(DISTROOT)/DEBIAN/control
		@echo '#! /bin/sh' > $(DISTROOT)/DEBIAN/postinst
		@echo '' >> $(DISTROOT)/DEBIAN/postinst
		@echo 'update-menus' >> $(DISTROOT)/DEBIAN/postinst
		@echo 'update-mime' >> $(DISTROOT)/DEBIAN/postinst
		@chmod 0755 $(DISTROOT)/DEBIAN/postinst
		@echo '#! /bin/sh' > $(DISTROOT)/DEBIAN/postrm
		@echo '' >> $(DISTROOT)/DEBIAN/postrm
		@echo 'update-menus' >> $(DISTROOT)/DEBIAN/postrm
		@echo 'update-mime' >> $(DISTROOT)/DEBIAN/postrm
		@chmod 0755 $(DISTROOT)/DEBIAN/postrm
		@rm -f $(DEBPKG)
		@dpkg-deb -v -b $(DISTROOT) $(DEBPKG)
		@rm -f -r $(DISTROOT)/DEBIAN

# BEGIN: deb package dependency resolving block
# {
    # non-escape patterns
    PATTERN_01 = s|^Depends: ||g;s|([^)]*)||g;s|,||g;s|  | |g
    PATTERN_02 = ,
    PATTERN_03 = (
    PATTERN_04 = )
    PATTERN_05 = (%)
    PATTERN_06 = =
    PATTERN_07 = (>=
    # generate a list of required packages for the binary file
    BIN_PKG_DEPS = $(sort $(shell dpkg -S $(filter /%, $(shell ldd $(BINFILE) 2> /dev/null)) 2> /dev/null | sed -e 's|:.*||g'))
    # generate a list of user defined packages for the binary file
    USER_PKG_DEPS = $(PKGDEPENDS)
    # add user defined packages to required packages
    BIN_USER_PKG_DEPS = $(sort $(BIN_PKG_DEPS) $(USER_PKG_DEPS))
    # generate a list of all dependencies for each required package (ignore user defined packages)
    RECURSIVE_PKG_DEPS = $(sort $(shell dpkg -s $(BIN_PKG_DEPS) 2> /dev/null | grep '^Depends:' | sed -e "$(PATTERN_01)"))
    # remove packages which are already included by other packages (recursive dependencies)
    DISTINCT_PKG_DEPS = $(filter-out $(RECURSIVE_PKG_DEPS),$(BIN_USER_PKG_DEPS))
    # append version information for each package available on the system
    GET_PKG_VERSION = $(shell dpkg -s $(PACKAGE) 2> /dev/null | grep '^Version:' | sed -e 's|Version: ||g')
    RESOLVE_PKG_DEPS = $(foreach PACKAGE,$(DISTINCT_PKG_DEPS),$(if $(GET_PKG_VERSION),$(PACKAGE) $(PATTERN_07)$(GET_PKG_VERSION)$(PATTERN_04),$(PACKAGE))$(PATTERN_02))
# }
# END

